var questions = [
    "that you can't say a funeral",
    "dogs are actually saying when they bark",
    "that grown-ups wish they could still do",
    "you should never put in your mouth",
    "not to do in a hospital",
    "that you wish you hadn't eaten",
    "not to tell your mom",
    "people do when no one is looking",
    "that is harder than it looks",
    "that you love to eat",
    "that is hard to transport",
    "that goes bad",
    "that says your life is going downhill",
    "that make you feel stupid",
    "that is a waste of space",
    "you wish there was more of",
    "that must be magic",
    "that is so boring you can't stand it",
    "that shouldn't be included in video games",
    "that shouldn't be passed to the next generation",
    "that smells terrible",
    "that you often trip over",
    "you shouldn't throw off a building",
    "that you wouldn't do in an elevator",
    "no one should ever wear",
    "you'll do to stay warm",
    "you might find in a library",
    "you'd return if they were christmas gifts",
    "you are grateful for",
    "you are ungrateful for",
    "you do to get ready for winter",
    "you do to get a job",
    "you do to relieve stress",
    "you get on black friday",
    "you shouldn't attempt to juggle",
    "you shouldn't do when naked",
    "you shouldn't lick",
    "you shouldn't say to your in-laws",
    "you wished you had when you were a kid",
    "you shouldn't say when walking out of the bathroom",
    "you shouldn't carve into a pumpkin",
    "that you wish for",
    "a psychic would say",
    "you would buy if you were rich",
    "you would do if you were 50 feet tall",
    "you would bring on a deserted island",
    "that makes for the best dessert",
    "that you'd rather forget",
    "your parents forgot to tell you",
    "your grandparents forgot to tell you",
    "your dentist forgot to tell you",
    "your lawyer forgot to tell you",
    "your teacher forgot to tell you",
    "your sister forgot to tell you",
    "you will do when you retire",
    "that would get a doctor sued",
    "that gives you a headache",
    "you wouldn't want to clean",
    "children shouldn't know",
    "women know more about than men",
    "men know about more than men",
    "girls have to deal with that guys don't",
    "men have have to deal with that women don't",
    "you think should be nicer",
    "you shouldn't say at thanksgiving",
    "you wish you could steal",
    "you wish you could do",
    "that would be strange to include on a resume",
    "that there should be an award for",
    "you shouldn't do when having dinner with the queen",
    "you shouldn't make fun of",
    "that needs to be made fun of",
    "that makes you giggle",
    "that everyone else but you thinks is funny",
    "that you shouldn't do in the office",
    "that makes ballet more exciting",
    "you would say to a cat if it could talk",
    "you would say to a pig if it could talk",
    "you would say to a dog if it could talk",
    "you say to get rid of unwanted guests",
    "you would line up to see or do",
    "that you don't pay attention to",
    "that you obsess over",
    "that would make a good punchline",
    "that confirms you are guilty",
    "that tires you out",
    "tell you that your house is haunted",
    "that you can't mix",
    "that shouldn't be mixed",
    "that would be interesting to mix",
    "that you wish weren't mixed",
    "that you just can't believe",
    "about women that frustrate you",
    "about men that frustrate you",
    "that is harder than it looks",
    "that is easier than it looks",
    "that is just as hard as it looks",
    "that cause trouble",
    "you wouldn't want to be allergic to",
    "that you need to survive",
    "you shouldn't do in a car",
    "you shouldn't do on vacation",
    "you would wish for if you found a genie",
    "that confirms you are losing your memory",
    "that take forever",
    "that you wish you could see again for the first time"
];
module.exports = {
    questions
}