var questions = [
    "that you can't say a funeral",
    "dogs are actually saying when they bark",
    "that grown-ups wish they could still do",
    "you should never put in your mouth",
    "not to do in a hospital",
    "that you wish you hadn't eaten",
    "not to tell your mom",
    "people do when no one is looking",
    "that is harder than it looks",
    "that you love to eat",
    "that is hard to transport",
    "that goes bad",
    "that says your life is going downhill",
    "that makes you feel stupid",
    "that is a waste of space",
    "you wish there was more of",
    "that must be magic",
    "that is so boring you can't stand it",
    "that shouldn't be included in video games",
    "that shouldn't be passed to the next generation",
    "that smells terrible",
    "that you often trip over",
    "you shouldn't throw off a building",
    "that you wouldn't do in an elevator",
    "no one should ever wear",
    "you'll do to stay warm",
    "you might find in a library",
    "you'd return if they were christmas gifts",
    "you are grateful for",
    "you are ungrateful for",
    "you do to get ready for winter",
    "you do to get a job",
    "you do to relieve stress",
    "you get on black friday",
    "you shouldn't attempt to juggle",
    "you shouldn't do when naked",
    "you shouldn't lick",
    "you shouldn't say to your in-laws",
    "you wished you had when you were a kid",
    "you shouldn't say when walking out of the bathroom",
    "you shouldn't carve into a pumpkin",
    "that you wish for",
    "a psychic would say",
    "you would buy if you were rich",
    "you would do if you were 50 feet tall",
    "you would bring on a deserted island",
    "that makes for the best dessert",
    "that you'd rather forget",
    "your parents forgot to tell you",
    "your grandparents forgot to tell you",
    "your dentist forgot to tell you",
    "your lawyer forgot to tell you",
    "your teacher forgot to tell you",
    "your sister forgot to tell you",
    "you will do when you retire",
    "that would get a doctor sued",
    "that gives you a headache",
    "you wouldn't want to clean",
    "children shouldn't know",
    "women know more about than men",
    "men know about more than women",
    "girls have to deal with that guys don't",
    "men have have to deal with that women don't",
    "you think should be nicer",
    "you shouldn't say at thanksgiving",
    "you wish you could steal",
    "you wish you could do",
    "that would be strange to include on a resume",
    "that there should be an award for",
    "you shouldn't do when having dinner with the queen",
    "you shouldn't make fun of",
    "that needs to be made fun of",
    "that makes you giggle",
    "that everyone else but you thinks is funny",
    "that you shouldn't do in the office",
    "that makes ballet more exciting",
    "you would say to a cat if it could talk",
    "you would say to a pig if it could talk",
    "you would say to a dog if it could talk",
    "you say to get rid of unwanted guests",
    "you would line up to see or do",
    "that you don't pay attention to",
    "that you obsess over",
    "that would make a good punchline",
    "that confirms you are guilty",
    "that tires you out",
    "that tells you that your house is haunted",
    "that you can't mix",
    "that shouldn't be mixed",
    "that would be interesting to mix",
    "that you wish weren't mixed",
    "that you just can't believe",
    "about women that frustrate you",
    "about men that frustrate you",
    "that is harder than it looks",
    "that is easier than it looks",
    "that is just as hard as it looks",
    "that cause trouble",
    "you wouldn't want to be allergic to",
    "that you need to survive",
    "you shouldn't do in a car",
    "you shouldn't do on vacation",
    "you would wish for if you found a genie",
    "that confirms you are losing your memory",
    "that takes forever",
    "that you wish you could see again for the first time",
    "that you never tell your parents about",
    "that you always tell your parents about",
    "that cannibals think about while dining",
    "that drives you nuts",
    "dogs are actually saying when they bark",
    "you wish you didn't have to touch",
    "that you wish you had",
    "grown-ups wish they still had",
    "a paramedic shouldn't shout",
    "you do when no one is looking",
    "that is good",
    "you wish you could eat more of",
    "that you don't eat often enough",
    "that confirms a house is haunted",
    "that confirms food has gone bad",
    "happens in Vegas",
    "that makes you uncomfortable",
    "that must be magic",
    "that smells wonderful",
    "that smells strange",
    "that you might find in the kitchen",
    "that you might find in the bathroom",
    "that you might find in the bedroom",
    "that you wish wasn't cancelled",
    "that you would kill a homeless person for",
    "that you would kidnap someone for",
    "that you wish you could do in an elevator",
    "you might wear to a wedding",
    "that you shouldn't bring to a wedding",
    "that you might forget when going to a wedding",
    "that you can never find",
    "that you can always find",
    "that you shouldn't do on black friday",
    "you shouldn't do on your birthday",
    "you have to do on your birthday",
    "you shouldn't give as birthday gift",
    "you should give as birthday gift",
    "you shouldn't celebrate",
    "that makes you shiver",
    "that you shouldn't lick",
    "that you shouldn't play catch with",
    "you wish you could draw a picture of",
    "that you wish you could carve into a pumpkin",
    "that you shouldn't carve into a pumpkin",
    "that should be in a divorce settlement",
    "that should never be in a divorce settlement",
    "that you just can't give up",
    "you would buy if you were wish",
    "you would do if you were a giant",
    "you would do if you were tiny",
    "you would rather forget",
    "that tend to put off until tommorrow",
    "you would wish for if stranded on an island",
    "should be in every movie",
    "your friends text you",
    "your parents would kill you for",
    "that would get a doctor sued",
    "that gives you a headache",
    "you hate to clean",
    "you love to clean",
    "that makes you go ahhhh",
    "that would make ballet more exciting",
    "a chicken would cross a road for",
    "dogs say to other dogs",
    "a dentist should never say to a patient",
    "you hope will happen next year",
    "a cow thinks about while being milked",
    "a waiter shouldn't do",
    "about men that frustrates you",
    "about women that frustrates you",
    "cats think about humans",
    "an ideal spouse would do for you",
    "children't shouldn't know",
    "fish think about their aquarium",
    "kids know more about that adults",
    "firefighters do betwen fires",
    "that people like about you",
    "that people don't like about you",
    "that is better late than never",
    "that is embarrassing",
    "that proves you are in a bad restauraunt",
    "people think they understand but don't",
    "that is politically incorrect",
    "that is wild",
    "that is useless",
    "that is impossible to measure",
    "that is none of your business",
    "that confirms you are losing your memory",
    "that confirms you are guilty",
    "that should go in a time capsule",
    "that shouldn't go in a time capsule",
    "that comes with a manual",
    "that takes courage",
    "that makes you feel better",
    "that would get you fired",
    "you would go back in time for",
    "you would go forward in time for",
    "you would die for",
    "you would live for",
    "that would warrant an apology",
    "that you would go back to school for",
    "that you would eat alive",
    "that shouldn't be in a hotel",
    "that needs to be in a hotel",
    "that you would cry without",
    "that women talk about when they all go to the restroom together",
    "that men talk about in the restroom",
    "you call your friends",
    "you can't believe someone actually did",
    "you use for an excuse when you're late for work",
    "you can't stop",
    "you didn't realize until it was too late",
    "you dream about",
    "you hate about the hospital",
    "you don't want in your bed",
    "you could eat in a salad",
    "you would never eat as a salad",
    "that you keep in your car",
    "that just can not be beat",
    "you like to hide",
    "you wish you could shop for",
    "you need to survive",
    "you never see in the country",
    "you never see in the USA",
    "that Texas is famous for",
    "that you never see in the city",
    "that you never see on television",
    "that you always see on television",
    "that scare you about getting older",
    "that you say to a telemarketer",
    "you should keep to yourself",
    "that might send you to the hospital",
    "you shouldn't attempt as an older person",
    "you shouldn't accept from strangers",
    "you shouldn't call your kids",
    "you shouldn't celebreate",
    "you shouldn't advertise in the classified",
    "that says a craigslist ad is sketchy",
    "you shouldn't say in a job interview",
    "that you should never do in a job interview",
    "that you shouldn't advertise on billboards",
    "you shouldn't collect",
    "you shouldn't display in your house",
    "you shouldn't do at the beach",
    "that would make your join the circus",
    "you shouldn't do while babysitting",
    "you worry about when trying to fall asleep",
    "that keeps your from sleeping",
    "you wish would/had happened on your honeymoon",
    "you shouldn't do on your honeymoon",
    "you shouldn't do quickly",
    "you have to do quickly",
    "you shouldn't do while naked",
    "you shouldn't do with glue",
    "you shouldn't doodle on",
    "you shouldn't experiment with",
    "you shouldn't lend to neighbors",
    "you shouldn't mess with",
    "you shouldn't post on internet",
    "you shouldn't put on your front lawn",
    "that might send you to group therapy",
    "you shouldn't shout at the top of your lungs",
    "that you shouldn't teach your parrot to play",
    "that children's books shouldn't be about",
    "you shouldn't write on a valentines card",
    "you use to remove snow",
    "you shouldn't try to hold onto",
    "you wish people would stop talking about",
    "you wish you could borrow",
    "that you wish grew on trees",
    "that should never grow on trees"

];

var answers = [
    "A Gypsy curse",
    "A moment of silence",
    "An honest cop with nothing left to lose",
    "Famine",
    "Flesh-eating bacteria",
    "Shapeshifters",
    "A time travel paradox",
    "Authentic Mexican cuisine",
    "Bling",
    "Consultants",
    "Crippling debt",
    "Daddy issues",
    "The Donald Trump Seal of Approval",
    "Laying an egg",
    "Getting naked and watching Nickelodeon",
    "Pretending to care",
    "Boogers",
    "The inevitable heat death of the universe",
    "The miracle of childbirth",
    "The Rapture",
    "White privilege",
    "Wifely duties",
    "The Hamburglar",
    "AXE Body Spray",
    "Horrifying laser hair removal accidents",
    "Agriculture",
    "Natural selection",
    "Michelle Obama's arms",
    "The World of Warcraft",
    "Swooping",
    "Obesity",
    "All-you-can-eat shrimp for $499",
    "Domino's Oreo Dessert Pizza",
    "Hot cheese",
    "Raptor attacks",
    "Alcoholism",
    "A middle-aged man on roller skates",
    "The Care Bear Stare",
    "Oversized lollipops",
    "Self-loathing",
    "Children on leashes",
    "Being on fire",
    "Teenage pregnancy",
    "Leaving an awkward voicemail",
    "Uppercuts",
    "Customer service representatives",
    "Science",
    "Flightless birds",
    "A balanced breakfast",
    "Actually taking candy from a baby",
    "The Make-A-Wish Foundation",
    "A clandestine butt scratch",
    "Passive-aggressive Post-it notes",
    "The Chinese gymnastics team",
    "Switching to Geico",
    "Peeing a little bit",
    "Home video of Oprah sobbing into a Lean Cuisine",
    "Powerful thighs",
    "Winking at old people",
    "Fancy Feast",
    "Being rich",
    "Sweet, sweet vengeance",
    "Republicans",
    "A gassy antelope",
    "Natalie Portman",
    "Kamikaze pilots",
    "The Kool-Aid Man",
    "Free samples",
    "A big hoopla about nothing",
    "Doing the right thing",
    "World peace",
    "RoboCop",
    "Oompa-Loompas",
    "Inappropriate yodeling",
    "Puberty",
    "Ghosts",
    "Vigorous jazz hands",
    "GoGurt",
    "Police brutality",
    "Preteens",
    "Tweeting",
    "Expecting a burp and vomiting on the floor",
    "Adderall",
    "Emotions",
    "Licking things to claim them as your own",
    "Spontaneous human combustion",
    "Finger painting",
    "Old-people smell",
    "Dying of dysentery",
    "My inner demons",
    "A Super Soaker full of cat pee",
    "Cuddling",
    "Friendly fire",
    "A disappointing birthday party",
    "Mathletes",
    "A tiny horse",
    "Riding off into the sunset",
    "An M Night Shyamalan plot twist",
    "Mutually-assured destruction",
    "Yeast",
    "Grave robbing",
    "Eating the last known bison",
    "Catapults",
    "Poor people",
    "Forgetting the Alamo",
    "The Hustle",
    "The Force",
    "Loose lips",
    "Getting really high",
    "Scientology",
    "Frolicking",
    "Crystal meth",
    "Serfdom",
    "Stranger danger",
    "A Bop It",
    "Prancing",
    "Vigilante justice",
    "Overcompensation",
    "A lifetime of sadness",
    "Racism",
    "Sunshine and rainbows",
    "Flash flooding",
    "The terrorists",
    "Attitude",
    "Breaking out into song and dance",
    "Leprosy",
    "The heart of a child",
    "Puppies!",
    "Waking up half-naked in a Denny's parking lot",
    "Active listening",
    "Ethnic cleansing",
    "The Little Engine That Could",
    "The invisible hand",
    "Unfathomable stupidity",
    "Re-gifting",
    "White people",
    "Too much hair gel",
    "Cheating in the Special Olympics",
    "Charisma",
    "Pooping back and forth Forever",
    "Menstruation",
    "Kids with ass cancer",
    "A salty surprise",
    "The South",
    "Being fabulous",
    "Centaurs",
    "Chivalry",
    "Lunchables",
    "The profoundly handicapped",
    "Heartwarming orphans",
    "Fiery poops",
    "Tangled Slinkys",
    "The true meaning of Christmas",
    "Estrogen",
    "A zesty breakfast burrito",
    "That thing that electrocutes your abs",
    "Passing a kidney stone",
    "Soup that is too hot",
    "Five-Dollar Footlongs",
    "A really cool hat",
    "Teaching a robot to love",
    "Count Chocula",
    "Wearing underwear inside-out to avoid doing laundry",
    "A death ray",
    "The glass ceiling",
    "A cooler full of organs",
    "The American Dream",
    "When you fart and a little bit comes out",
    "Take-backsies",
    "Saxophone solos",
    "Italians",
    "Amputees",
    "My relationship status",
    "Bees?",
    "College",
    "8 oz of sweet Mexican black-tar heroin",
    "Object permanence",
    "Opposable thumbs",
    "Chainsaws for hands",
    "Child beauty pageants",
    "Explosions",
    "Sniffing glue",
    "Repression",
    "A murder most foul",
    "Giving 110 percent",
    "The Trail of Tears",
    "Being marginalized",
    "Goblins",
    "Hope",
    "My soul",
    "A hot mess",
    "Vikings",
    "Hot people",
    "An Oedipus complex",
    "Geese",
    "Global warming",
    "New Age music",
    "Hot Pockets",
    "Making a pouty face",
    "Vehicular manslaughter",
    "Elderly Japanese men",
    "Exchanging pleasantries",
    "Parting the Red Sea",
    "Spectacular abs",
    "Figgy pudding",
    "A mopey zoo lion",
    "A bag of magic beans",
    "Poor life choices",
    "A thermonuclear detonation",
    "The Big Bang",
    "Land mines",
    "Friends who eat all the snacks",
    "Goats eating cans",
    "The Dance of the Sugar Plum Fairy",
    "Me time",
    "The Underground Railroad",
    "A sea of troubles",
    "Morgan Freeman's voice",
    "Women in yogurt commercials",
    "Being a sorcerer",
    "Grandma",
    "Friction",
    "Party poopers",
    "Farting and walking away",
    "Booby-trapping the house to foil burglars",
    "Dying",
    "Hurricane Katrina",
    "The folly of man",
    "Men",
    "The Amish",
    "Pterodactyl eggs",
    "Team-building exercises",
    "A brain tumor",
    "Fear itself",
    "A low standard of living",
    "A nuanced critique",
    "A rival dojo",
    "A web of lies",
    "A woman scorned",
    "Apologizing",
    "Appreciative snapping",
    "Being a dinosaur",
    "Dorito breath",
    "Fabricating statistics",
    "Finding a skeleton",
    "Gandalf",
    "Genetically engineered super-soldiers",
    "Getting abducted by Peter Pan",
    "Good grammar",
    "Hipsters",
    "Jafar",
    "Mad hacky-sack skills",
    "Leveling up",
    "Media coverage",
    "Medieval Times Dinner and Tournament",
    "Moral ambiguity",
    "My machete",
    "One thousand Slim Jims",
    "Ominous background music",
    "Overpowering your father",
    "Quiche",
    "Santa Claus",
    "Slow motion",
    "Space muffins",
    "Statistically validated stereotypes",
    "Sudden Poop Explosion Disease",
    "The economy",
    "The harsh light of day",
    "The hiccups",
    "Being a busy adult"
];
module.exports = {
    questions,
    answers
}