const questions = [
    "Where did you mostly grow up",
    "What was your first car",
    "What was your favorite subject in school/high school/college",
    "Where did you serve a mission",
    "What was your first job",
    "What were some of your hobbies growing up",
    "What is your hobby now",
    "What's your favorite kind of vacation",
    "What is your favorite animal",
    "What's your favorite tv show",
    "What do you do to relax",
    "What's your favorite form of exercise",
    "Are you a night owl or a morning person",
    "Did you play a sport in high school",
    "Do you have a favorite sports team",
    "What is your favorite food",
    "What is your favorite dessert",
    "What is your favorite movie",
    "What is your favorite outdoor activity",
    "Who is the prophet you most remember as a child or youth",
    "What is your job",
    "What is your favorite board game",
];
const McGhieAnswers = [
    "Cupertino, CA",
    "Plymouth Satellite",
    "Music (Band/Choir/Orchestra)",
    "Okayama, Japan",
    "Paper boy",
    "Sports (all, but especially basketball)",
    "Anime",
    "Staying at home and relaxing",
    "Ryan’s dog wiggles”",
    "Kaguya wants to be confessed to",
    "Play video games (DOTA)",
    "Going for a walk",
    "Neither. I like my sleep.",
    "Yes. Football, basketball, tennis",
    "Orangutan Gangsters",
    "MOD Pizza",
    "Ice Cream",
    "Man of La Mancha",
    "Picnic",
    "David O McKay",
    "Software Engineer",
    "Spot It",
];
const MurrayAnswers = [
    "Lancaster, California",
    "Toyota Celica",
    "Math",
    "Buenos Aires South Argentina and Dallas Texas",
    "Fast Food - Weinerschnitzel",
    "Space, Skateboarding and Surfing",
    "Skateboarding, Volleyball and Computers",
    "Disney!",
    "Penguins or my Westie Missy",
    "Hallmark Movies",
    "Work in the yard",
    "Gardening or Wii Just Dance",
    "Neither",
    "Golf and Basketball",
    "Seahawks and LA Lakers",
    "Cereal",
    "Ice Cream Shakes or Fudge",
    "Tomorrowland",
    "Boogie Boarding or Surfing or Miniature Golf",
    "Spencer W Kimball",
    "Systems Analyst",
    "Disney Music Trivia or Yahtzee"
];

const EllenAnswers = [
    "Dallas, Texas",
    "Dodge Neon",
    "Social Studies",
    "I didn't serve",
    "Pharmacy Technician",
    "The Sims and band",
    "Reading, Baking, and Home Decor",
    "Beach Vacations",
    "Dogs",
    "America's Test Kitchen",

    "I never relax",
    "Refit",
    "Night Owl",
    "Soccer",
    "I don't watch sports",
    "Carbs",
    "Cookies",
    "Anything with peanut butter and chocolate",
    "Pride and Prejudice",
    "Bike Rides",
    "Monson",
    "None",
    "Settlers of Catan"
];
var DaybellAnswers = [
    "Heber City, UT",
    "Ford Pinto",
    "HS (Sports & girls)/College (Math)",
    "Ohio/Pennsylvania",
    "Railroad worker",
    "Hunting, Fishing, Tae Kwon Do",
    "Reading, Traveling",
    "Anything with all my kids and grandkids",
    "Dog",
    "Big Bang Theory",
    "Read",
    "Tae Kwon Do or Running",
    "Night Owl",
    "Basketball, Football and Track",
    "Anyone but the Patriots",
    "Mexican",
    "German chocolate cake",
    "Ferris Buellers Day off",
    "Running or Hiking",
    "David O’ McKay",
    "CEO",
    "Candy Land"
];

module.exports = {
    questions,
    answers: {
        "McGhie": McGhieAnswers,
        "Murray": MurrayAnswers,
        "Daybell": DaybellAnswers,
    }
}